mkdir: cannot create directory ‘runs/try_d20’: File exists
2025-05-15 01:36:39.569699: W external/tsl/tsl/framework/bfc_allocator.cc:296] Allocator (GPU_0_bfc) ran out of memory trying to allocate 9.56GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.
Traceback (most recent call last):
  File "/n/netscratch/pehlevan_lab/Lab/ml/ICL-structured-data/NONLINEAR/experiment/remote/kappasweep_neurips/kappasweep.py", line 45, in <module>
    state, hist = train(config, data_iter=iter(trainobject), batch_size=np.min([1000,n]), loss='mse', test_every=1000, train_iters=30000, optim=optax.adamw,lr=1e-4)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/netscratch/pehlevan_lab/Lab/ml/ICL-structured-data/NONLINEAR/experiment/remote/kappasweep_neurips/../../../trainmini.py", line 166, in train
    state = create_train_state(init_rng, model, mini_samp_x, optim=optim, **opt_kwargs) # the samp_x data is not used during this initialisation
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/netscratch/pehlevan_lab/Lab/ml/ICL-structured-data/NONLINEAR/experiment/remote/kappasweep_neurips/../../../trainmini.py", line 41, in create_train_state
    params = model.init(rng, dummy_input)['params']
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/netscratch/pehlevan_lab/Lab/ml/ICL-structured-data/NONLINEAR/experiment/remote/kappasweep_neurips/../../../model/transformer.py", line 289, in __call__
    y = TransformerBlock(
        ^^^^^^^^^^^^^^^^^
  File "/n/netscratch/pehlevan_lab/Lab/ml/ICL-structured-data/NONLINEAR/experiment/remote/kappasweep_neurips/../../../model/transformer.py", line 180, in __call__
    x = SingleHeadSelfAttention(self.config)(inputs, decoder_mask, idxs=idxs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/netscratch/pehlevan_lab/Lab/ml/ICL-structured-data/NONLINEAR/experiment/remote/kappasweep_neurips/../../../model/transformer.py", line 107, in __call__
    attn_weights = jnp.einsum('...qd,...kd->...qk', query, key)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/home05/mletey/.conda/envs/try4/lib/python3.12/site-packages/jax/_src/numpy/lax_numpy.py", line 3494, in einsum
    return einsum(operands, contractions, precision,  # type: ignore[operator]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/home05/mletey/.conda/envs/try4/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 10269581216 bytes.
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
